# Generated by Django 5.0 on 2024-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscategory_remove_new_user_views_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
