# Generated by Django 5.0 on 2024-07-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
