# Generated by Django 4.2.14 on 2024-07-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerapp', '0003_profile'),
        ('core', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costumer_views',
            field=models.ManyToManyField(to='costumerapp.costumer'),
        ),
    ]
