# Generated by Django 5.0 on 2024-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_views_qty'),
        ('costumerapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costumer_views',
            field=models.ManyToManyField(blank=True, to='costumerapp.costumer'),
        ),
    ]
