# Generated by Django 5.0 on 2024-07-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costumerapp.profile'),
        ),
    ]
